# Generated by Django 2.1.2 on 2018-11-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField(max_length=10000)),
                ('movie_link', models.TextField(max_length=100000)),
            ],
        ),
    ]
